### ISSUE TITLE
openssl dependency isn't explicitely checked

### ISSUE THREAD

**Issue by MightyMoose504** [justchokingaround/lobster#167]
It allows me to search and select a show or movie but when it tries to load it the script fails. possibly a mistake on my end. Ive attached my log file. Thanks for the help!
[lobster.log](https://github.com/justchokingaround/lobster/files/13277982/lobster.log)

OS: Fedora Workstation 38

**Comment by justchokingaround** [comment]
it failed during description, that can happen sometimes when the keys change. could u try again?

**Comment by MightyMoose504** [comment]
Its been a persistent issue for the last couple of days

**Comment by ahmad-reza619** [comment]
It doesn't work too on my machine. i'm using macbook M2 currently.
But the issue is that i cannot search for any movie. it shows `Error - No results found`

I followed the [installation method for mac](https://github.com/justchokingaround/lobster#mac) btw

**Comment by pitsi** [comment]
I get the base64 error since yesterday (Nov. 8th). Here is my log
[lobster.log](https://github.com/justchokingaround/lobster/files/13303824/lobster.log)

In case it helps, the enikey variable may be broken, because it depends on this url which leads to 404.
`https://github.com/enimax-anime/key/`

p.s. I have no issue with search, it returns results as it should.

**Comment by justchokingaround** [comment]
update the script, i pushed a fix for the ley yesterday night

**Comment by ahmad-reza619** [comment]
![Screenshot 2023-11-09 at 18 30 23](https://github.com/justchokingaround/lobster/assets/52902060/f9b62abd-5981-42aa-bb3d-96a129f7645d)
![Screenshot 2023-11-09 at 18 31 37](https://github.com/justchokingaround/lobster/assets/52902060/459daf27-6482-4da8-a273-e9232eee452a)

still not working for me on mac. i Provided the normal & debug output in above.

**Comment by pitsi** [comment]
It did not work for me earlier, but after one try it did. Proof
```
$ lobster 
Search Movie/TV Show: doom patrol
$ lobster 
Search Movie/TV Show: deadpool
Now Playing - Deadpool
```
It returned no results at the first try with doom patrol, it just exited. If you use vidcloud as a provider, try with upcloud (or the other way round) using the -p switch. Just make sure you type **V**idcloud and **U**p**C**loud there.

**Comment by justchokingaround** [comment]
check that your `curl --version` is 8.4 or more. `8.1.2` will not work, so u might have to update ur curl. also make sure `brew install coreutils` is installed @ahmad-reza619

**Comment by MightyMoose504** [comment]
script is still no working for me. same issue. my curl vversion is the newest in the DNF repo ver 8.0.1
Is that an issue?

**Comment by justchokingaround** [comment]
yes, u need 8.4 or more

**Comment by ahmad-reza619** [comment]
@justchokingaround when i ran `curl --version` yes it was version 7.84. But the weird thing is that when i try to upgrade curl via homebrew, homebrew said that i already have 8.4 installed.

**Comment by ahmad-reza619** [comment]
Nvm i resolved the issue of curl, but still got same issue, cannot search for any movie

below is my `curl --version` output. `coreutils` also have been installed with version 9.4
```
curl 8.4.0 (aarch64-apple-darwin22.6.0) libcurl/8.4.0 (SecureTransport) OpenSSL/3.1.4 zlib/1.2.11 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libssh2/1.11.0 nghttp2/1.58.0 librtmp/2.3 OpenLDAP/2.6.6
Release-Date: 2023-10-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

**Comment by justchokingaround** [comment]
can u access flixhq.to in the browser?

**Comment by MightyMoose504** [comment]
Yes, it must be that issue with curl versions you spoke about. Its weird that the newest verison in the fedora 38 repo is 8.1.2 tho

**Comment by ahmad-reza619** [comment]
> can u access flixhq.to in the browser?

yes i can

**Comment by MightyMoose504** [comment]
can confirm script works on Linux mint with curl version 7.8.1 but it is not functioning on fedora 38
[lobster.log](https://github.com/justchokingaround/lobster/files/13334294/lobster.log)

**Comment by justchokingaround** [comment]
can you try running this command on fedora 38 and show me the output pls @MightyMoose504 :
```sh
printf "U2FsdGVkX1+GUJXaKXoVQBPC5ByfXkjHtij6WfUgLMuhPCMzvdjrjJ3YitfkWfVxGk/73yKjSETDenzaNWb78zQieM6C6BQvAK6yRn+91MeIYTpZKDWxQTfaVzfCJixYNlAGrbsRMlHIK69bHvry/e3z82Rdrlb7UxaQBk5L3MKE5Vp8O4ypZzv6r+VDYL0dO2vZNYlG02JLfMJa8L1Z/vcgspZzYRm62gDZVpzx2w9maJC7XzcS3llewxa/GqFTf6V8KOf1Bek+TEVtLHrx+yRl23r3W95i3HEx7jQKYDiqJPZNTYoAKEm9xn2LF7A5OwBkIJ7z3aRJL4QZ3w6n4Hg5rkkQUZEzjSEriGGEG6eImT+AcIFbggIHbSnC1FRtHS6cC5NSY7Q5PBdfmqyS+cMiEYH/m3OIlyd3UOqgxSj5C1a9fjpQ6uJlMRUgDmuFQCIyiCE+ucVj7Mn/s7cDty+ryUj/VsmCsfi+OChF3eAjMFMDJxrzmbI4WcjWq6Oa" | 
base64 -d | openssl enc -aes-256-cbc -d -md md5 -k oKOnRZFtLe3GD86GXw6 | sed -nE 's_.*"file":"([^"]*)".*_\1_p'
```

**Comment by justchokingaround** [comment]
also @ahmad-reza619 and @pitsi the script should be working now, regardless of your curl version

**Comment by MightyMoose504** [comment]
Works now lol. your not gonna believe this.....well you might, but I didn't have openssl installed. Didn't realize it wasn't as i guess it doesn't come preinstalled on Fedora. my bad

**Comment by justchokingaround** [comment]
oh ok, i should add it to the dependencies list, thanks for letting me know

**Comment by pitsi** [comment]
I have a small question, assuming that all issues above (including mine which had no output) are related to the key.
The key, no matter where it comes from, is parsed with curl every time the script runs, right? Wouldn't it be better to have the script download it in its folder inside ~/.config and reuse it from there?

For the record, I am on curl 8.4.0 and I do have openssl (3.0.11) installed.

**Comment by justchokingaround** [comment]
they change so often now, that caching isn't worth it

**Comment by ahmad-reza619** [comment]
@justchokingaround I'm still having this issue. I have updated it with -u flag but nothing changed

**Comment by justchokingaround** [comment]
send a log pls `lobster -x` and it's in `/tmp/lobster.log`

**Comment by ahmad-reza619** [comment]
Here it is. I think i have sent one too on discord though
```
+ debug=1
+ shift
+ '[' 0 -gt 0 ']'
++ printf %s ''
++ tr ' ' -
++ gsed 's/^-//g'
+ query=
+ '[' 0 = 1 ']'
+ '[' -z UpCloud ']'
+ '[' '' = 1 ']'
+ '[' '' = movie ']'
+ '[' '' = tv ']'
+ main
+ '[' -z '' ']'
+ '[' -z '' ']'
+ get_input
+ '[' 0 = 0 ']'
+ printf 'Search Movie/TV Show: '
Search Movie/TV Show: + read -r query
+ '[' -n voice ']'
++ echo voice
++ tr ' ' -
+ query=voice
+ '[' -z voice ']'
+ search voice
+ '[' 0 = 1 ']'
++ curl -s https://flixhq.to/search/voice
++ gsed ':a;N;$!ba;s/\n//g;s/class="flw-item"/\n/g'
++ gsed -nE 's@.*<a href=".*/(tv|movie)/watch-.*-([0-9]*)".*title="([^"]*)".*class="fdi-item">([^<]*)</span>.*@\3 (\1) [\4]\t\2@p'
++ tee /dev/null
+ response=
+ '[' -z '' ']'
+ send_notification Error 1000 '' 'No results found'
+ '[' 0 = 1 ']'
+ '[' 0 = 0 ']'
+ '[' -z 'No results found' ']'
+ '[' -n 'No results found' ']'
+ printf '\33[2K\r\033[1;34m%s - %s\n\033[0m' Error 'No results found'
[2K
[1;34mError - No results found
[0m+ return
+ exit 1
```

**Comment by justchokingaround** [comment]
what does `curl -s https://flixhq.to/search/voice -v` return?

**Comment by ahmad-reza619** [comment]
here is the output
```
*   Trying [64:ff9b::2456:3fb9]:443...
* Connected to flixhq.to (64:ff9b::2456:3fb9) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [5689 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=internetpositif.id
*  start date: Mar 29 00:00:00 2023 GMT
*  expire date: Apr 26 23:59:59 2024 GMT
*  subjectAltName does not match flixhq.to
* SSL: no alternative certificate subject name matches target host name 'flixhq.to'
* Closing connection
} [5 bytes data]
* TLSv1.3 (OUT), TLS alert, close notify (256):
} [2 bytes data]
```

I just realized here that https://flixhq.to/ is banned in my country lol. I guess i can access it in browser because i change dns to cloudflare. Probably have to change native dns in my mac now

**Comment by justchokingaround** [comment]
yep

**Comment by ahmad-reza619** [comment]
Confirmed, it works now 👍 thank you

**Comment by justchokingaround** [comment]
np
